name: bmi_tracker
description: "A new Flutter project."
publish_to: 'none'
version: 1.0.0+1

environment:
  sdk: ^3.10.7

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  firebase_core: ^3.2.0
  firebase_auth: ^5.1.2
  google_sign_in: ^6.2.1
  firebase_database: ^11.0.2
  intl: ^0.18.1
  fl_chart: ^0.63.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  flutter_native_splash: ^2.4.7
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo.png"
  min_sdk_android: 21

flutter_native_splash:
  color: "#ffffff"
  image: assets/logo.png
  android_12:
    image: assets/logo.png
    color: "#ffffff"

flutter:
  uses-material-design: true
  assets:
    - assets/logo.png
